//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solar_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginMaster
    {
        public int Id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string usertype { get; set; }
        public Nullable<bool> isactive { get; set; }
        public Nullable<System.DateTime> createddatetime { get; set; }
    }
}
