//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solar_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationMaster
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string EmailId { get; set; }
        public string MobileNumber { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string LastName { get; set; }
        public string gender { get; set; }
        public string U_id { get; set; }
        public string password { get; set; }
        public string c_password { get; set; }
    }
}
